trigger:
- main

pool:
  vmImage: Azure Pipelines

variables:
  imageName: 'pipelines-javascript-docker'

steps:
  - task: Docker@2
    inputs:
      command: 'build'
      repository: $(imageName)
      Dockerfile: app/Dockerfile
